baseURL = "https://ronaldbosma.github.io/"
languageCode = "en-us"
title = "Ronald's Blog"
theme = "mediumish"
summaryLength = 25
copyright = "Ronald Bosma - All rights reserved"
pygmentsCodeFences = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug"

[params]
  # description ="Ronald's Blog"

[params.author]
  name = "Ronald Bosma"
  thumbnail = "/images/author.webp"
  description = "Software Architect"

[params.index]
  picture = "/images/author.webp"
  title = "Ronald Bosma"
  subtitle = "Software Engineer & Architect"
  mdtext = '''I'm a software engineer & architect working for Info Support in the Netherlands. I have over 16 years of experience in building distributed systems with Microsoft technology.  

Since the start of my career I've had a deep interest in test automation. I'm a TDD enthusiast and in recent years I've come to appreciate Specification by Example and tools like Reqnroll. My interests also include Azure, Bicep, CI/CD and architecture.

So true: _&#34;The bitterness of poor quality remains long after the sweet taste of low price is forgotten.&#34;_'''
  alertbar = true

[params.social]
  github = "ronaldbosma"
  linkedin = "ronald-bosma"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Series"
    weight = 150
    identifier = "series"
    url = "/series"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "RSS"
    weight = 300
    identifier = "rss"
    url = "/index.xml"